# Generated by Django 4.2.4 on 2023-08-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='value',
            new_name='temperature',
        ),
    ]
